services:
  db-mysql:
    image: mysql:8.0
    container_name: db-mysql
    restart: always
    ports:
      - 9756:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: color123
      MYSQL_DATABASE: hono_db
    volumes:
      - data_mysql:/var/lib/mysql
    networks:
      - demo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
  db-redis:
    image: redis:alpine
    container_name: db-redis
    ports:
      - 9779:6379
    volumes:
      - data_redis:/data
    networks:
      - demo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 3
      start_period: 5s
  hono-service:
    build: ./server
    container_name: hono-service
    restart: unless-stopped
    ports:
      - 9750:9750
    environment:
      DATABASE_HOSTNAME: db-mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: color123
      DATABASE_NAME: hono_db
      REDIS_HOSTNAME: db-redis
      REDIS_PORT: 6379
      PORT: 9750
    depends_on:
      db-mysql:
        condition: service_healthy
      db-redis:
        condition: service_healthy
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge

volumes:
  data_mysql:
  data_redis:
